title: Staticast
baseline: The easiest way to publish your podcast
description: This is a demo of Staticast, the easiest way to publish your 🎙️ podcast.
keywords: [Podcast, Cecil, Static Site Generator]
author: Arnaud Ligny
copyright: Arnaud Ligny
baseurl: /
canonicalurl: true
language: en
date:
  format: j F Y
  timezone: Europe/Paris
output:
  pagetypeformats:
    section: ['html', 'rss', 'json']
theme:
  - podcast
  - garth
  - netlify-cms
  - netlify
  - serviceworker
icon: /logo.svg
assets:
  compile:
    variables:
      bodyColour: '#5a5a5a'
      linkColour: '#7E4EA3'
      backgroundColour: '#F1F3F4'
image: twitter-card.png
menus:
  footer:
    - name: Admin
      id: admin
      url: admin
      weight: 99
pagination:
  max: 10
podcast:
  owner:
    name: Arnaud Ligny
    email: arnaud@ligny.fr
  image: cover.png
  author: Arnaud Ligny
  categories:
    - Technology
  type: episodic
  explicit: "no"
  block: "no"
  newfeedurl: ""
  subscribe:
    - name: apple
      url: https://podcasts.apple.com/fr/podcast/staticast/id1520249637
      enabled: true
    - name: google
      url: https://podcasts.google.com/feed/aHR0cHM6Ly9zdGF0aWNhc3QubmV0bGlmeS5hcHAvZXBpc29kZXMvcnNzLnhtbA
      enabled: true
    - name: spotify
      url: https://open.spotify.com/show/6dlhe4G6Au5Zm7qX2M5tnS
      enabled: true
manifest:
  background_color: "#7E4EA3"
  theme_color: "#7E4EA3"
  icons:
    - src: manifest/icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: true
defaultpages:
  serviceworker:
    path: serviceworker
    layout: sw # override default layout
    output: js
netlify:
  redirects:
    - from: https://staticast-demo.netlify.app/*
      to: https://staticast-demo.cecil.app/:splat
      status: 301
      force: true
