title: "Staticast"
baseline: "The easiest way to diffuse your podcasts"
description: "The easiest way to diffuse your podcasts."
keywords: "Cecil, Static Site Generator, Podcast"
author: "Arnaud Ligny"
baseurl: "/"
canonicalurl: true
theme:
  - "podcast"
  - "garth"
