baseline: The easiest way to diffuse your podcast
theme:
  - podcast
  - garth
  - netlify-cms
  - netlify
  - serviceworker
podcast:
  author: Arnaud Ligny
  owner:
    name: Arnaud Ligny
    email: arnaud@ligny.fr
  image: cover.png
  categories:
    - Technology
  explicit: "false"
  type: episodic
  subscribe:
    - name: apple
      url: https://podcasts.apple.com/fr/podcast/staticast/id1520249637
      enabled: true
    - name: google
      url: https://podcasts.google.com/feed/aHR0cHM6Ly9zdGF0aWNhc3QubmV0bGlmeS5hcHAvZXBpc29kZXMvcnNzLnhtbA
      enabled: true
    - name: spotify
      url: https://open.spotify.com/show/6dlhe4G6Au5Zm7qX2M5tnS
      enabled: true
copyright: Arnaud Ligny
keywords: Cecil, Static Site Generator, Podcast
author: Arnaud Ligny
netlify:
  redirects:
    - from: https://staticast.netlify.app/*
      to: https://staticast.cecil.app/:splat
      status: 301
      force: true
description: Staticast is a podcast website template, powered by Cecil and can
  be deployed in few seconds with Netlify.
baseurl: /
canonicalurl: true
date:
  format: j F Y
  timezone: Europe/Paris
manifest:
  background_color: "#7E4EA3"
  theme_color: "#7E4EA3"
  icons:
    - src: manifest/icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: true
title: Staticast
icon: /logo.svg
menus:
  footer:
    - id: admin
      name: Admin
      url: admin
      weight: 99
pagination:
  max: 10
