title: "Staticast"
baseline: "The easiest way to diffuse your podcast"
description: "The easiest way to diffuse your podcast."
keywords: "Cecil, Static Site Generator, Podcast"
author: "Arnaud Ligny"
baseurl: "/"
canonicalurl: true
theme:
  - "podcast"
  - "garth"
  - "serviceworker"
icon: icon.svg
pagination:
  max: 10
manifest:
  background_color: '#7E4EA3'
  theme_color: '#7E4EA3'
  icons:
    - src: icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: true
podcast:
  author: Arnaud Ligny
  owner:
    name: Arnaud Ligny
    email: arnaud@ligny.fr
  image: cover.png
  listen:
    apple: https://podcasts.apple.com/fr/podcast/staticast/id1520249637
    spotify: https://open.spotify.com/show/6dlhe4G6Au5Zm7qX2M5tnS
    google: https://podcasts.google.com/feed/aHR0cHM6Ly9zdGF0aWNhc3QubmV0bGlmeS5hcHAvZXBpc29kZXMvcnNzLnhtbA
