title: Staticast
baseline: The easiest way to diffuse your podcast
description: Staticast is a podcast website template, powered by Cecil and can
  be deployed in few seconds with Netlify.
keywords: [Podcast, Cecil, Static Site Generator]
author: Arnaud Ligny
copyright: Arnaud Ligny
baseurl: /
canonicalurl: true
language: en
date:
  format: j F Y
  timezone: Europe/Paris
theme:
  - podcast
  - garth
  - netlify-cms
  - netlify
  - serviceworker
icon: /logo.svg
menus:
  footer:
    - name: Admin
      id: admin
      url: admin
      weight: 99
pagination:
  max: 10
podcast:
  owner:
    name: Arnaud Ligny
    email: arnaud@ligny.fr
  image: cover.png
  author: Arnaud Ligny
  categories:
    - Technology
  type: episodic
  explicit: "no"
  block: "no"
  newfeedurl: ""
  subscribe:
    - name: apple
      url: https://podcasts.apple.com/fr/podcast/staticast/id1520249637
      enabled: true
    - name: google
      url: https://podcasts.google.com/feed/aHR0cHM6Ly9zdGF0aWNhc3QubmV0bGlmeS5hcHAvZXBpc29kZXMvcnNzLnhtbA
      enabled: true
    - name: spotify
      url: https://open.spotify.com/show/6dlhe4G6Au5Zm7qX2M5tnS
      enabled: true
manifest:
  background_color: "#7E4EA3"
  theme_color: "#7E4EA3"
  icons:
    - src: manifest/icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: true
netlify:
  redirects:
    - from: https://staticast.netlify.app/*
      to: https://staticast.cecil.app/:splat
      status: 301
      force: true
