# Website options
title: Staticast
baseline: The easiest way to publish your podcast
description: This is a demo of Staticast, the easiest way to publish your 🎙️ podcast.
keywords: [Podcast, Cecil, Static Site Generator]
author: Arnaud Ligny
copyright: Arnaud Ligny
baseurl: /
canonicalurl: true
image: twitter-card.png
language: en
date:
  timezone: Europe/Paris
menus:
  main:
    - id: episodes
      enabled: false
  footer:
    - name: CMS
      id: admin
      url: admin
pagination:
  max: 10
theme:
  - podcast # Podcast player component
  - pwa     # Progressive Web App features
  - netlify # Netlify feature
  - netlify-cms # Netlify CMS support
manifest:
  background_color: "#7E4EA3"
  theme_color: "#7E4EA3"
  icons:
    - manifest/icon-192x192.png
    - manifest/icon-512x512.png
  shortcuts: true
serviceworker:
  enabled: true
  precache:
    - manifest/icon-192x192.png
    - manifest/icon-512x512.png

# Podcast options
podcast:
  owner:
    name: Arnaud Ligny
    email: arnaud@ligny.fr
  image: cover.png
  author: Arnaud Ligny
  categories:
    - Technology
  type: episodic
  subscribe:
    - name: apple
      title: Apple Podcasts
      url: https://podcasts.apple.com/fr/podcast/staticast/id1520249637
      enabled: true
    - name: google
      title: Google Podcasts
      url: https://podcasts.google.com/feed/aHR0cHM6Ly9zdGF0aWNhc3QubmV0bGlmeS5hcHAvZXBpc29kZXMvcnNzLnhtbA
      enabled: true
    - name: spotify
      title: Spotify
      url: https://open.spotify.com/show/6dlhe4G6Au5Zm7qX2M5tnS
      enabled: true
  hoster:
    - name: Arnaud Ligny
      avatar: https://github.com/arnaudligny.png?s=150
      twitter: "@arnaudligny"

# Cecil options
output:
  pagetypeformats:
    homepage: html
    section: [html, rss]
defaultpages:
  # overrides serviceworker default layout
  serviceworker:
    path: serviceworker
    layout: sw
    output: js
netlify:
  redirects:
    # redirect demo
    - from: https://staticast-demo.netlify.app/*
      to: https://staticast-demo.cecil.app/:splat
      status: 301
      force: true
