title: "Staticast"
baseline: "The easiest way to diffuse your podcasts"
description: "The easiest way to diffuse your podcasts."
keywords: "Cecil, Static Site Generator, Podcast"
author: "Arnaud Ligny"
baseurl: "/"
canonicalurl: true
theme:
  - "podcast"
  - "garth"
  - "serviceworker"
icon: icon.svg
manifest:
  background_color: '#7E4EA3'
  theme_color: '#D4DBDE'
  icons:
    - src: icon-512x512.png
      sizes: 512x512
      type: image/png
serviceworker:
  enabled: true
