[build]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh"
  publish = "_site"
  environment = { PHP_VERSION = "7.2", CECIL_VERSION = "5.33.1" }

[context.deploy-preview]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh preview"
[context.deploy-preview.environment]
  CECIL_SERVICEWORKER_ENABLED = "false"

[context.branch-deploy]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh preview"
[context.branch-deploy.environment]
  CECIL_SERVICEWORKER_ENABLED = "false"

[template.environment]
  #CECIL_TITLE = "Podcast's title"
  #CECIL_BASELINE = "Short description (~ 20 characters)"
  #CECIL_DESCRIPTION = "Full description (~ 250 characters)"
  #CECIL_AUTHOR = "Website's author"
  #CECIL_COPYRIGHT = "Website's copyright"
  #CECIL_PODCAST_AUTHOR = "Podcast's author"
  #CECIL_PODCAST_OWNER_NAME = "Podcast's owner name"
  #CECIL_PODCAST_OWNER_EMAIL = "Podcast's owner email"
