backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "static/"
public_folder: "/"
logo_url: https://cecil.app/images/cecil-logo-netlify-cms.png
show_preview_links: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - label: "Episodes"
    name: "episodes"
    label_singular: "Episode"
    description: >
      Podcast episodes.
    folder: "content/episodes"
    create: true
    preview_path: "episodes/{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false, required: true}
      - {label: "Description", name: "body", widget: "markdown"}
      - label: "Episode"
        name: "episode"
        widget: "object"
        fields:
          - {label: "MP3 file", name: "file", widget: "file", required: true}
    sortable_fields: ['title', 'date']
  - label: "Pages"
    name: "pages"
    label_singular: "Page"
    description: >
      Single pages.
    delete: false
    preview_path: "{{title}}"
    files:
      - label: "Home"
        name: "index"
        file: "content/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Home"}
          - {label: "Text", name: "body", widget: "markdown"}
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "About"}
          - {label: "Text", name: "body", widget: "markdown"}
          - {label: "Menu", name: "menu", widget: "string", default: "main"}
  - label: "Settings"
    name: "settings"
    description: >
      Site settings.
    delete: false
    editor:
      preview: false
    files:
      - label: "Configuration"
        name: "config"
        file: "config.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Cecil", required: true}
          - {label: "Baseline", name: "baseline", widget: "string", default: "Your blog's butler.", required: true}
          - {label: "Description", name: "description", widget: "string", default: "A ready to use static blog, powered by Cecil and Hyde.", required: true}
          - {label: "Base URL", name: "baseurl", widget: "string", default: "/", required: true, hint: "With a trailing slash."}
          - {label: "Use canonical URL", name: "canonicalurl", widget: "boolean", default: true, required: true}
          - {label: "Theme", name: "theme", widget: "list", required: true}
          - {label: "Icon", name: "icon", widget: "image", default: "icon.svg", required: true}
          - label: "Menus"
            name: "menus"
            widget: "object"
            fields:
              - label: "Footer"
                name: "footer"
                widget: "list"
                fields:
                - {label: "Identifier", name: "id", widget: "string", required: true}
                - {label: "Name", name: "name", widget: "string", required: true}
                - {label: "URL", name: "url", widget: "string"}
                - {label: "Position", name: "weight", widget: "number"}
          - label: "Date"
            name: "date"
            widget: "object"
            fields:
              - {label: "Format", name: "format", widget: "string", default: "j F Y", required: true}
              - {label: "Time zone", name: "timezone", widget: "string", default: "Europe/Paris", required: true}
          - label: "Pagination"
            name: "pagination"
            widget: "object"
            fields:
              - {label: "Pages by page", name: "max", widget: "number", default: "10"}
          - label: "Podcast"
            name: podcast
            widget: "object"
            fields:
              - {label: "Author", name: "author", widget: "string", required: true}
              - label: "Owner"
                name: "owner"
                widget: "object"
                fields:
                  - {label: "Name", name: "name", widget: "string", required: true}
                  - {label: "Email", name: "email", widget: "string", required: true}
              - {label: "Cover", name: "image", widget: "image", required: true}
              - label: "Categories"
                name: "categories"
                widget: "select"
                multiple: true
                options: ["Arts", "Business", "Comedy", "Education", "Fiction", "Government", "History", "Health & Fitness", "Kids & Family", "Leisure", "Music", "News", "Religion & Spirituality", "Science", "Society & Culture", "Sports", "Technology", "True Crime", "TV & Film"]
              - label: "Explicit"
                name: "explicit"
                widget: "select"
                options:
                  - { label: "No", value: "false" }
                  - { label: "Yes", value: "true" }
                default: ["No"]
              - label: "Type"
                name: "type"
                widget: "select"
                options:
                  - { label: "Episodic", value: "episodic" }
                  - { label: "Serial", value: "serial" }
                default: ["episodic"]
              - label: "Subscribe"
                name: "subscribe"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string", required: true}
                  - {label: "URL", name: "url", widget: "string", required: true}
                  - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
