backend:
  name: git-gateway
  branch: master
  squash_merges: true
local_backend: true # https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
publish_mode: editorial_workflow
media_folder: "assets/"
public_folder: "/"
logo_url: https://cecil.app/images/cecil-logo-netlify-cms.png
show_preview_links: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - label: "Episodes"
    name: "episodes"
    label_singular: "Episode"
    description: >
      Podcast episodes.
    folder: "content/episodes"
    summary: "# {{episode.number}} · {{title}} · {{date | date('DD MMM YYYY')}} · {{episode.type}}"
    create: true
    preview_path: "episodes/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false, required: true}
      - {label: "Description", name: "body", widget: "markdown"}
      - label: "Episode"
        name: "episode"
        widget: "object"
        fields:
          - {label: "MP3 file", name: "file", widget: "file", required: true}
          - {label: "Season", name: "season", widget: "number", default: 0, value_type: "int", required: false}
          - {label: "Number", name: "number", widget: "number", default: 0, value_type: "int", required: false}
          - label: "Type"
            name: "type"
            widget: "select"
            options:
              - { label: "Full", value: "full" }
              - { label: "Trailer", value: "trailer" }
              - { label: "Bonus", value: "bonus" }
            default: ["full"]
            required: false
          - label: "Explicit"
            name: "explicit"
            widget: "select"
            options:
              - { label: "No", value: "no" }
              - { label: "Yes", value: "yes" }
            default: ["no"]
            required: false
            hint: >
              Explicit content warning: drugs, inflammatory speech, profanity, sexual references/depictions, violence, etc.
          - label: "Block"
            name: "block"
            widget: "select"
            options:
              - { label: "No", value: "no" }
              - { label: "Yes", value: "yes" }
            default: ["no"]
            required: false
            hint: >
              If you want to remove your show from Apple Podcasts and Google Podcasts platforms.
    sortable_fields: ['title', 'date', 'episode.number']
    view_filters:
      - label: "Full"
        field: episode.type
        pattern: 'full'
      - label: "Trailer"
        field: episode.type
        pattern: 'trailer'
      - label: "Bonus"
        field: episode.type
        pattern: 'bonus'
      - label: Explicit
        field: explicit
        pattern: false
  - label: "Pages"
    name: "pages"
    label_singular: "Page"
    description: >
      Single pages.
    delete: false
    preview_path: "{{slug}}"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "About", required: true}
          - {label: "Text", name: "body", widget: "markdown", required: true}
          - {label: "Menu", name: "menu", widget: "string", default: "main", required: true}
  - label: "Settings"
    name: "settings"
    description: >
      Site settings.
    delete: false
    editor:
      preview: false
    files:
      - label: "Configuration"
        name: "config"
        file: "config.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Staticast", required: true}
          - {label: "Baseline", name: "baseline", widget: "string", required: true}
          - {label: "Description", name: "description", widget: "string", required: true}
          - {label: "Keywords", name: "keywords", widget: "list", required: false}
          - {label: "Author", name: "author", widget: "string", required: false}
          - {label: "Copyright", name: "copyright", widget: "string", required: false}
          - {label: "Base URL", name: "baseurl", widget: "string", default: "/", required: true, hint: "With a trailing slash."}
          - {label: "Use canonical URL", name: "canonicalurl", widget: "boolean", default: true, required: true}
          - {label: "Language", name: "language", widget: "string", default: 'en', required: true, hint: "The two-letter language code (ISO 639-1)."}
          - label: "Date"
            name: "date"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Format", name: "format", widget: "string", default: "j F Y", required: true}
              - {label: "Time zone", name: "timezone", widget: "string", default: "Europe/Paris", required: true}
          - {label: "Theme(s)", name: "theme", widget: "list", required: true}
          - {label: "Image", name: "image", widget: "image", default: "twitter-card.png", required: false, hint: Used for social share.}
          - label: "Menus"
            name: "menus"
            widget: "object"
            collapsed: true
            fields:
              - label: "Footer"
                name: "footer"
                widget: "list"
                fields:
                - {label: "Identifier", name: "id", widget: "string", required: true}
                - {label: "Name", name: "name", widget: "string", required: true}
                - {label: "URL", name: "url", widget: "string"}
                - {label: "Position", name: "weight", widget: "number"}
          - label: "Pagination"
            name: "pagination"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Pages by page", name: "max", widget: "number", default: "10", required: false}
          - label: "Podcast"
            name: podcast
            widget: "object"
            fields:
              - label: "Owner"
                name: "owner"
                widget: "object"
                collapsed: true
                summary: "{{fields.name}} ({{fields.email}})"
                fields:
                  - {label: "Name", name: "name", widget: "string", required: true}
                  - {label: "Email", name: "email", widget: "string", required: true}
                hint: >
                  Required to add the podcast to Apple Podcasts or Google Podcasts platforms.
              - {label: "Cover image", name: "image", widget: "image", required: true}
              - {label: "Author", name: "author", widget: "string", required: false}
              - label: "Categories"
                name: "categories"
                widget: "select"
                multiple: true
                options: ["Arts", "Business", "Comedy", "Education", "Fiction", "Government", "History", "Health & Fitness", "Kids & Family", "Leisure", "Music", "News", "Religion & Spirituality", "Science", "Society & Culture", "Sports", "Technology", "True Crime", "TV & Film"]
                required: false
                hint: >
                  The general topic of the podcast to be shown in the Search results.
              - label: "Type"
                name: "type"
                widget: "select"
                options:
                  - { label: "Episodic", value: "episodic" }
                  - { label: "Serial", value: "serial" }
                default: ["episodic"]
                required: false
              - label: "Explicit"
                name: "explicit"
                widget: "select"
                options:
                  - { label: "No", value: "no" }
                  - { label: "Yes", value: "yes" }
                default: ["no"]
                required: false
                hint: >
                  Explicit content warning: drugs, inflammatory speech, profanity, sexual references/depictions, violence, etc.
              - label: "Block"
                name: "block"
                widget: "select"
                options:
                  - { label: "No", value: "no" }
                  - { label: "Yes", value: "yes" }
                default: ["no"]
                required: false
                hint: >
                  If you want to remove your show from Apple Podcasts and Google Podcasts platforms.
              - {label: "New feed URL", name: "newfeedurl", widget: "string", required: false, hint: "Only if you move your feed."}
              - label: "Platforms"
                name: "subscribe"
                label_singular: "Platform"
                widget: "list"
                summary: "{{fields.title}} (enabled: {{fields.enabled}})"
                add_to_top: true
                fields:
                  - {label: "Name", name: "name", widget: "string", required: true}
                  - {label: "Title", name: "title", widget: "string", required: true}
                  - {label: "URL", name: "url", widget: "string", required: true}
                  - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
              - label: "Hosters"
                name: "hoster"
                label_singular: "Hoster"
                widget: "list"
                summary: "{{fields.name}} ({{fields.twitter}})"
                add_to_top: true
                fields:
                  - {label: "Name", name: "name", widget: "string", required: true}
                  - {label: "Avatar", name: "avatar", widget: "string", required: true}
                  - {label: "Twitter", name: "twitter", widget: "string", required: true, hint: "The twitter handle must start with a \"@\"."}
